### ISSUE TITLE
Support for CloudFormation Stack Policies

### ISSUE THREAD

**Issue by atward** [delfick/bespin#10]
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/protect-stack-resources.html

**Comment by delfick** [comment]
I think this would be better put into https://github.com/delfick/aws_syncr than bespin.

Unfortunately I'm not sure I have the time to spend on this.

Sorry.

**Comment by atward** [comment]
aws_syncr seems like a scan+update tool. We'd like to use CloudFormation's native functionality to prevent changes.

**Comment by delfick** [comment]
yeah, so you'd use aws_syncr to apply the stack resources to the stack.

aws_syncr is better suited for that because it already has logic around creating the policy structure and it handles the idea of updating an existing resource.

**Comment by atward** [comment]
Support added in [stack_policy branch](https://github.com/atward/bespin/tree/stack_policy). Blocked on/Coupled with boto3 support (#17).

**Comment by delfick** [comment]
cool, looks good to me
