### ISSUE TITLE
Determining account id requires role

### ISSUE THREAD

**Issue by atward** [delfick/bespin#12]
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Something went wrong! -- BespinError
	"There are no roles in your account, I can't figure out the account id"
```
This can be done without the need for roles via [sts:GetCallerIdentity](http://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html)

**Comment by delfick** [comment]
I merged in the PR to use GetCallerIdentity
