### ISSUE TITLE
Stack parameters are required

### ISSUE THREAD

**Issue by atward** [delfick/bespin#36]
Some CF templates do not require parameters, so omitting `params_json` and `params_yaml` should be valid from an end user perspective.

Is there any history behind why stack parameters are required? See:
- [bespin_specs.py#L45](https://github.com/delfick/bespin/blob/2dfdf7976a924251a5b4d3469e6fff5fd6158ec0/bespin/option_spec/bespin_specs.py#L45)
- https://github.com/delfick/bespin/commit/120f0fbc7cf3fa282aabcca9518a2ab782a5c138

Defining an empty mapping (`params_yaml: {}`) is a workaround for anyone affected by this.

**Comment by delfick** [comment]
I can't remember why I did that. It's possible that at the time boto required parameters? *shrugs*

**Comment by atward** [comment]
Upon further investigation of this issue it became apparent that by forcing users to specify either params_yaml or params_json, neither of their default values could ever be evaluated.

Will raise a PR to remove these defaults and make absence of both params_yaml and params_json return empty parameters.

**Comment by atward** [comment]
Fixed in #39
